apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd
  namespace: podinfo
spec:
  releaseName: etcd
  chart:
    spec:
      chart: etcd
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/etcd/values.yaml
#  values:
#    metrics:
#      enabled: true
